"""initial schema

Revision ID: 17344347d302
Revises:
Create Date: 2026-06-24 22:33:22.026430
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "17344347d302"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charging_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("station_id", sa.String(length=64), nullable=False),
        sa.Column("id_tag", sa.String(length=64), nullable=False),
        sa.Column("energy_kwh", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("charging_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_charging_sessions_station_id"), ["station_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_charging_sessions_status"), ["status"], unique=False)

    op.create_table(
        "partners",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("unsettled_amount", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("partners", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_partners_name"), ["name"], unique=False)

    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("records", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sync_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sync_runs_source"), ["source"], unique=False)

    op.create_table(
        "locations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("partner_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_locations_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_locations_partner_id"), ["partner_id"], unique=False)

    op.create_table(
        "charging_stations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("location_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("charging_stations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_charging_stations_location_id"), ["location_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_charging_stations_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("charging_stations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_charging_stations_status"))
        batch_op.drop_index(batch_op.f("ix_charging_stations_location_id"))

    op.drop_table("charging_stations")
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_locations_partner_id"))
        batch_op.drop_index(batch_op.f("ix_locations_name"))

    op.drop_table("locations")
    with op.batch_alter_table("sync_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_runs_source"))

    op.drop_table("sync_runs")
    with op.batch_alter_table("partners", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_partners_name"))

    op.drop_table("partners")
    with op.batch_alter_table("charging_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_charging_sessions_status"))
        batch_op.drop_index(batch_op.f("ix_charging_sessions_station_id"))

    op.drop_table("charging_sessions")
    # ### end Alembic commands ###
